"""
Constrained credit portfolio selection prototype.

Run from the project root:
    .venv/bin/python src/credit_risk/portfolio_optimization.py

Uses out-of-fold random-forest PD estimates from model_validation.py.
The optimisation maximises selected exposure subject to:
  1. a total exposure cap,
  2. an expected-loss budget,
  3. a maximum number of selected accounts.

Important limitations:
- Historical UCI dataset; not production lending data.
- Credit limit is only an EAD proxy.
- LGD, exposure cap, loss budget, and account limit are illustrative.
- The random-forest predictions were generated by a model that included sex.
  This requires careful fairness/legal review before any real-world use.
- Exact duplicate rows are excluded from the candidate pool to avoid
  counting identical records twice. Without customer IDs, this is an assumption.
- Actual outcomes are used only for a retrospective diagnostic after selection,
  never as optimisation inputs.
"""

from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import Bounds, LinearConstraint, milp


ROOT = Path(__file__).resolve().parents[2]
DATA_PATH = ROOT / "data" / "raw" / "credit_card_default.csv"
PREDICTIONS_PATH = ROOT / "reports" / "cross_validation_predictions.csv"
REPORTS = ROOT / "reports"

TARGET = "default_payment_next_month"
MODEL_NAME = "Random forest"

# Illustrative policy constraints; edit these for scenario analysis.
LGD_ASSUMPTION = 0.45
TOTAL_EXPOSURE_LIMIT = 100_000_000
EXPECTED_LOSS_BUDGET = 5_000_000
MAX_SELECTED_ACCOUNTS = 1_000
EAD_PROXY_CAP = 600_000
RANDOM_STATE = 42


def main():
    REPORTS.mkdir(parents=True, exist_ok=True)

    for path in (DATA_PATH, PREDICTIONS_PATH):
        if not path.exists():
            raise FileNotFoundError(
                f"Required file not found: {path}\n"
                "Run src/credit_risk/model_validation.py first and check the dataset path."
            )

    data = pd.read_csv(DATA_PATH)
    predictions = pd.read_csv(PREDICTIONS_PATH)

    required_data = {TARGET, "credit_limit"}
    required_predictions = {
        "row_index",
        "actual_default",
        "model",
        "oof_predicted_pd",
    }

    missing_data = required_data - set(data.columns)
    missing_predictions = required_predictions - set(predictions.columns)

    if missing_data:
        raise ValueError(f"Dataset is missing columns: {sorted(missing_data)}")
    if missing_predictions:
        raise ValueError(
            f"Predictions file is missing columns: {sorted(missing_predictions)}"
        )

    model_predictions = predictions.loc[
        predictions["model"].eq(MODEL_NAME)
    ].copy()

    if model_predictions.empty:
        raise ValueError(
            f"No predictions found for model '{MODEL_NAME}' in "
            f"{PREDICTIONS_PATH.name}."
        )

    # Map source row references back to the source data.
    data = data.copy()
    data["row_index"] = data.index
    candidates = model_predictions.merge(
        data[["row_index", "credit_limit", TARGET]],
        on="row_index",
        how="inner",
        validate="one_to_one",
    )

    # Remove exact duplicate source records from the optimisation candidate
    # pool. With no customer identifier, this is a documented assumption.
    duplicate_mask = data.drop(columns=["row_index"]).duplicated(keep="first")
    unique_row_indices = set(data.loc[~duplicate_mask, "row_index"])
    before_dedup = len(candidates)
    candidates = candidates.loc[
        candidates["row_index"].isin(unique_row_indices)
    ].copy()
    removed_duplicates = before_dedup - len(candidates)

    candidates["pd_estimate"] = candidates["oof_predicted_pd"].clip(0.0, 1.0)
    candidates["ead_proxy"] = (
        pd.to_numeric(candidates["credit_limit"], errors="coerce")
        .fillna(0)
        .clip(lower=0, upper=EAD_PROXY_CAP)
    )
    candidates["expected_loss_proxy"] = (
        candidates["pd_estimate"]
        * LGD_ASSUMPTION
        * candidates["ead_proxy"]
    )

    # Accounts with zero exposure cannot contribute to the objective.
    candidates = candidates.loc[candidates["ead_proxy"] > 0].reset_index(drop=True)

    if candidates.empty:
        raise ValueError("No positive-exposure candidates remain.")

    n = len(candidates)
    ead = candidates["ead_proxy"].to_numpy(dtype=float)
    expected_loss = candidates["expected_loss_proxy"].to_numpy(dtype=float)

    # Binary decision x_i: 1 = include candidate i, 0 = exclude.
    # scipy.milp minimises, so negate EAD to maximise total selected exposure.
    objective = -ead
    constraints_matrix = np.vstack(
        [
            ead,
            expected_loss,
            np.ones(n, dtype=float),
        ]
    )

    constraints = LinearConstraint(
        constraints_matrix,
        lb=np.array([-np.inf, -np.inf, -np.inf]),
        ub=np.array(
            [
                TOTAL_EXPOSURE_LIMIT,
                EXPECTED_LOSS_BUDGET,
                MAX_SELECTED_ACCOUNTS,
            ],
            dtype=float,
        ),
    )

    print("=" * 72)
    print("CONSTRAINED CREDIT PORTFOLIO OPTIMISATION")
    print("=" * 72)
    print(f"Model PD source: {MODEL_NAME} out-of-fold predictions")
    print(f"Candidate rows after exact-deduplication: {n:,}")
    print(f"Exact duplicate rows excluded: {removed_duplicates:,}")
    print(f"LGD assumption: {LGD_ASSUMPTION:.0%}")
    print(f"Total exposure limit: {TOTAL_EXPOSURE_LIMIT:,.0f}")
    print(f"Expected-loss budget: {EXPECTED_LOSS_BUDGET:,.0f}")
    print(f"Maximum selected accounts: {MAX_SELECTED_ACCOUNTS:,}")
    print("Solving mixed-integer optimisation problem ...")

    result = milp(
        c=objective,
        integrality=np.ones(n, dtype=int),
        bounds=Bounds(np.zeros(n), np.ones(n)),
        constraints=constraints,
        options={"time_limit": 120},
    )

    if result.x is None:
        raise RuntimeError(
            "The optimiser did not return a feasible solution. "
            f"Solver status: {result.message}"
        )

    candidates["selected"] = result.x > 0.5
    selected = candidates.loc[candidates["selected"]].copy()

    if selected.empty:
        raise RuntimeError(
            "The optimiser returned an empty portfolio. Review constraints."
        )

    selected["observed_default_label"] = np.where(
        selected[TARGET].astype(int).eq(1), "Yes", "No"
    )

    selected_exposure = float(selected["ead_proxy"].sum())
    selected_ecl = float(selected["expected_loss_proxy"].sum())
    selected_accounts = len(selected)
    selected_mean_pd = float(
        np.average(selected["pd_estimate"], weights=selected["ead_proxy"])
    )
    selected_ecl_rate = (
        selected_ecl / selected_exposure if selected_exposure else np.nan
    )

    # Retrospective outcome diagnostic only; not used in the optimiser.
    observed_default_rate = float(selected[TARGET].mean())

    summary = pd.DataFrame(
        [
            {
                "solver_status": result.message,
                "model": MODEL_NAME,
                "candidate_accounts": n,
                "selected_accounts": selected_accounts,
                "lgd_assumption": LGD_ASSUMPTION,
                "exposure_limit": TOTAL_EXPOSURE_LIMIT,
                "selected_exposure_proxy": selected_exposure,
                "expected_loss_budget": EXPECTED_LOSS_BUDGET,
                "selected_expected_loss_proxy": selected_ecl,
                "selected_exposure_weighted_mean_pd": selected_mean_pd,
                "expected_loss_to_selected_exposure": selected_ecl_rate,
                "max_selected_accounts": MAX_SELECTED_ACCOUNTS,
                "retrospective_observed_default_rate": observed_default_rate,
                "retrospective_outcome_note": (
                    "Diagnostic only; actual outcomes were not optimisation inputs."
                ),
                "duplicate_rows_excluded": removed_duplicates,
            }
        ]
    )

    selected_output = selected[
        [
            "row_index",
            "selected",
            "observed_default_label",
            "pd_estimate",
            "ead_proxy",
            "expected_loss_proxy",
        ]
    ].sort_values(
        ["expected_loss_proxy", "ead_proxy"],
        ascending=[False, False],
    )

    summary_path = REPORTS / "portfolio_optimization_summary.csv"
    selected_path = REPORTS / "optimized_portfolio_accounts.csv"
    summary.to_csv(summary_path, index=False)
    selected_output.to_csv(selected_path, index=False)

    print()
    print(f"Solver status: {result.message}")
    print(f"Selected accounts: {selected_accounts:,}")
    print(f"Selected exposure proxy: {selected_exposure:,.2f}")
    print(f"Expected-loss proxy: {selected_ecl:,.2f}")
    print(f"Exposure-weighted mean PD: {selected_mean_pd:.2%}")
    print(f"Expected loss / selected exposure: {selected_ecl_rate:.2%}")
    print(
        "Retrospective observed default rate among selected rows: "
        f"{observed_default_rate:.2%}"
    )
    print()
    print("Saved outputs:")
    print(f"  {summary_path}")
    print(f"  {selected_path}")
    print()
    print(
        "Interpretation caution: this is a constrained selection exercise, "
        "not a lending recommendation. There are no observed loan prices, "
        "interest margins, funding costs, recovery data, sector labels, or "
        "regulatory constraints in this dataset. Exposure and loss limits are "
        "illustrative and must not be presented as bank policy."
    )


if __name__ == "__main__":
    main()
